/*  eslint-disable no-unused-vars */

export enum TanstackKeys {
    CalendarEvent = "calendarEvent",
    CalendarEvents = "calendarEvents",
    CourseCardSettings = "courseCardSettings",
    Courses = "courses",
    StarredCourses = "starrredCourses",
    UnstarredCourses = "unstarredCourses",
    CourseCardsRank = "courseCardsRank",
    CourseFeatures = "courseFeatures",
    CourseBasic = "courseBasic",
    CourseCalendarEvents = "courseCalendarEvents",
    CourseFolderResources = "courseFolderResources",
    CourseParticipants = "courseParticipants",
    CourseResourcesBySearch = "courseResourcesBySearch",
    CourseRootResources = "courseRootResources",
    CourseTasklistDailyWorkflow = "courseTasklistDailyWorkflow",
    CourseAllResources = "courseAllResources",
    CourseFavorite = "courseFavorite",
    LightbulletinComment = "lightbulletinComment",
    Bulletin = "bulletin",
    LightbulletinAllComments = "lightbulletinAllComments",
    LightbulletinResources = "lightbulletinResources",
    LightbulletinAddComment = "lightbulletinAddComment",
    LightbulletinNotifications = "lightbulletinNotifications",
    LightbulletinUpdateComment = "lightbulletinUpdateComment",
    LightbulletinsForCourse = "lightbulletinsForCourse",
    DELETEinstantMessage = "DELETEinstantMessage",
    DELETEinstantMessageThread = "DELETEinstantMessageThread",
    Messagesv2 = "messagesv2",
    MessagesRecipientsSearch = "messagesRecipientsSearch",
    Messagesv3 = "messagesv3",
    Messages = "messages",
    POSTinstantMessagev2 = "POSTinstantMessagev2",
    POSTmessageAttachment = "POSTmessageAttachment",
    PUTinstantMessageThread = "PUTinstantMessageThread",
    PUTinstantMessageThreadUpdateIsRead = "PUTinstantMessageThreadUpdateIsRead",
    NotificationsTopMenu = "notificationsTopMenu",
    Notifications = "notifications",
    CurrentUser = "currentUser",
    Person = "person",
    PersonsRelations = "personsRelations",
    SsoUrl = "ssoUrl",
    PersonalFollowUpTasks = "personalFollowUpTasks",
    PersonalTasks = "personalTasks",
    PersonalTasklistDailyWorkflow = "personalTasklistDailyWorkflow"
}
